### ISSUE TITLE
NewConnectionError

### ISSUE THREAD

**Issue by FeXd** [FeXd/saskwildfire#3]
```
Traceback (most recent call last):
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x109114370>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='environment.gov.sk.ca', port=80): Max retries exceeded with url: /firefiles/DailyFireDangerMaps/tomorrow_fwi.pdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109114370>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arlin/Git/saskwildfire/main.py", line 89, in <module>
    download_file(item['path'], './pdf/', item['pdf'])
  File "/Users/arlin/Git/saskwildfire/main.py", line 39, in download_file
    response = requests.get(url+file, stream=True)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='environment.gov.sk.ca', port=80): Max retries exceeded with url: /firefiles/DailyFireDangerMaps/tomorrow_fwi.pdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109114370>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```

**Comment by FeXd** [comment]
Happened again.

Pasting output just in case it is different, but I think it's the same.

```
Traceback (most recent call last):
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x107edda30>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='environment.gov.sk.ca', port=80): Max retries exceeded with url: /firefiles/activefires.pdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107edda30>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arlin/Git/saskwildfire/main.py", line 93, in <module>
    download_file(item['path'], './pdf/', item['pdf'])
  File "/Users/arlin/Git/saskwildfire/main.py", line 40, in download_file
    response = requests.get(url+file, stream=True)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/arlin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='environment.gov.sk.ca', port=80): Max retries exceeded with url: /firefiles/activefires.pdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107edda30>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```

Possibly related: https://stackoverflow.com/questions/47375153/requests-get-in-python-giving-connection-timeout-error

Perhaps I should just change the timeout to be a few minutes?
